### PR TITLE
deleted categories no longer show up on posts

### LINKED ISSUE #115: BUG WHEN DELETING CATEGORY
When deleting category that is associated with a post, FK constraint error occurs. Change the hard delete to a soft delete and make sure that deleted categories are not visible on posts that still exist

### PR DESCRIPTION
**Pull request by CrystalElseyNSS**
### Changes

- Added filter to Post.js to only render Category JSX for categories that aren't deleted

### Testing
- Delete a category that is associated with a post
- Make sure the category doesn't appear on the post

### CODE REVIEW

**Comment by iamdrewkirkland** [comment]
Deleted categories still appear in the list when adding a new post however the deleted category conditional render is working correctly.

**Review by durrjp — APPROVED** [review]
Categories that are deleted are no longer showing up on post list, OR in the add post form, OR in the edit post form. Looks great!

**Comment by sarah-hart-landolt** [comment]
it works!

**Review by durrjp — APPROVED** [review]
New way of editing post without a category selected works now

**Pull request merged**
